-- AceBank Schema Initialization (safe for repeated execution)
-- No DROP statements: uses CREATE TABLE IF NOT EXISTS

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AADHAAR_NO VARCHAR(12) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) DEFAULT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Accounts table
CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_NO INT PRIMARY KEY,
    USER_ID INT,
    ACCOUNT_TYPE ENUM('SAVINGS', 'CHECKING', 'LOAN') DEFAULT 'SAVINGS',
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS ENUM('ACTIVE', 'BLOCKED', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- Loan applications table
CREATE TABLE IF NOT EXISTS LOAN_APPLICATIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NO INT NOT NULL,
    LOAN_TYPE VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TENURE INT NOT NULL DEFAULT 1,
    PURPOSE TEXT,
    STATUS ENUM('PENDING', 'APPROVED', 'REJECTED') DEFAULT 'PENDING',
    APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_NO) REFERENCES ACCOUNTS(ACCOUNT_NO) ON DELETE CASCADE
);

-- Transactions table
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ACCOUNT INT NULL,
    RECEIVER_ACCOUNT INT NULL,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TX_TYPE ENUM('TRANSFER', 'DEPOSIT', 'WITHDRAWAL') NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO),
    FOREIGN KEY (RECEIVER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO)
);

-- Performance indexes
-- Note: MySQL does not support "IF NOT EXISTS" on CREATE INDEX. On first run these
-- succeed; on subsequent runs they raise error 1061 (duplicate key name), which the
-- schema executor catches and ignores, keeping initialization idempotent.
CREATE INDEX idx_accounts_user ON ACCOUNTS(USER_ID);
CREATE INDEX idx_tx_sender ON TRANSACTIONS(SENDER_ACCOUNT, CREATED_AT);
CREATE INDEX idx_tx_receiver ON TRANSACTIONS(RECEIVER_ACCOUNT);
CREATE INDEX idx_loan_account ON LOAN_APPLICATIONS(ACCOUNT_NO);
CREATE INDEX idx_users_email ON USERS(EMAIL);
